name: OneCloud-Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git qemu-user-static pigz bc jq
          chmod +x compile.sh

      - name: Build Armbian
        run: |
          # 删除了被弃用的 KERNEL_ONLY 参数
          sudo ./compile.sh \
            BOARD=onecloud \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=img

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Armbian-Onecloud-Final
          path: output/images/*.img*
